# Generated by Django 5.2.7 on 2025-10-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, default='Agadir', max_length=100, null=True),
        ),
    ]
