# Generated by Django 5.2.7 on 2025-10-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='profil.jpg', upload_to='img'),
        ),
    ]
